apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: "https://github.com/<your_github_username>/Continuous-Integration-and-Continuous-Delivery-CI-CD.git"
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: flake8
      taskRef:
        name: flake8
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: nose
      taskRef:
        name: nose
      runAfter:
        - flake8
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: buildah
      taskRef:
        name: buildah
      runAfter:
        - nose
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: deploy
      taskRef:
        name: deploy
      runAfter:
        - buildah
      workspaces:
        - name: source
          workspace: shared-workspace
